# Generated by Django 4.2.6 on 2023-10-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='E:/2do/Trabajos independientes/Aimas-web/web-aimas-2/backend/projects/src/IDENTIDAD BISNE-10.png', upload_to='ruta/donde/subir'),
        ),
    ]
