# Generated by Django 4.2.6 on 2023-10-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='./src/IDENTIDAD BISNE-10.png', upload_to='ruta/donde/subir'),
        ),
    ]
