# Generated by Django 4.2.6 on 2023-10-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='https://drive.google.com/file/d/1edRPGsRoz5yrgRSzelmtBdpR8Fs9wA-3/view?usp=share_link', upload_to='ruta/donde/subir')),
                ('type', models.CharField(choices=[('OP1', 'Opción 1'), ('OP2', 'Opción 2'), ('OP3', 'Opción 3')], default='OP1', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='https://drive.google.com/file/d/1edRPGsRoz5yrgRSzelmtBdpR8Fs9wA-3/view?usp=share_link', upload_to='ruta/donde/subir'),
        ),
    ]
