# Generated by Django 4.2.6 on 2023-10-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_site_project_url_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='https://www.dropbox.com/scl/fi/wu1xid6dtow5gtfxd3dn1/IDENTIDAD-BISNE-10.png?rlkey=1e41wybiozla8f3tenw0sbyip&dl=0', upload_to='https://www.dropbox.com/home/Apps/Web%20Aimas%20Studio'),
        ),
    ]
